balancer:
  build: .
  ports:
  - 80:80
  restart: always
  links:
  - frontend1
  – frontend2
frontend1:
  build: ../frontend1/Dockerfile
  restart: always
frontend2:
  build: ../frontend2/Dockerfile
  restart: always
